services:
  - type: web
    name: iss-chroma-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install torch==1.13.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
      pip install -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: MONGO_URI
        sync: false
